### ISSUE TITLE
Create an Application for Producing Messages

### ISSUE THREAD

**Issue by SchroederSteffen** [SAPDocuments/Issues#139]
Tutorials: https://developers.sap.com/tutorials/cp-enterprisemessaging-nodejs-producing-app.html
--------------------------

Hi Team,

We noticed that the sample code for the manifest.yml in the above tutorial contains invalid indentation for the 'env' parameters.
After the empty line, env: starts at the beginning of the line but should be indented like the other parameters.

Furthermore, the same sample code misses quotation marks at the end of the "service" values in the SAP_XBEM_BINDINGS environment variable. The values need to be replaced anyways but the missing quotation marks resulted in issues for multiple colleagues.

Could you please fix it?

Cheers,
Steffen

**Comment by pradeeppanda-sap** [comment]
fixed.

**Comment by SchroederSteffen** [comment]
Hi,
I checked the sample code and it's still not correct.
The indentation isn't fixed and the quotation marks for the two address fields in the SAP_XBEM_BINDINGS environment variables are wrong.

It reads:
```
applications:
  - name: producer
    host: producer-host
    domain: <REPLACE WITH YOUR DOMAIN>
    buildpack: 'https://github.com/cloudfoundry/nodejs-buildpack'
    memory: 256M
    health-check-type: none
    path: .
    command: node producer.js
    services:
      - <REPLACE WITH YOUR MESSAGING SERVICE>
env:
  SAP_JWT_TRUST_ACL: '[{"clientid":"*","identityzone":"*"}]'
  SAP_XBEM_BINDINGS: |
    {
      "inputs": {},
      "outputs": {
        "myOutA" : {
          "service": "<REPLACE WITH YOUR MESSAGING SERVICE>",
          "address": topic:"<REPLACE WITH YOUR TOPIC>",
          "reliable": false
        },
        "myOutB" : {
          "service": "<REPLACE WITH YOUR MESSAGING SERVICE>",
          "address": topic:"<REPLACE WITH YOUR TOPIC>",
          "reliable": false
        }
      }
    }
```

while it should read:

```
applications:
  - name: producer
    host: producer-host
    domain: <REPLACE WITH YOUR DOMAIN>
    buildpack: 'https://github.com/cloudfoundry/nodejs-buildpack'
    memory: 256M
    health-check-type: none
    path: .
    command: node producer.js
    services:
      - <REPLACE WITH YOUR MESSAGING SERVICE>
    env:
      SAP_JWT_TRUST_ACL: '[{"clientid":"*","identityzone":"*"}]'
      SAP_XBEM_BINDINGS: |
        {
          "inputs": {},
          "outputs": {
            "myOutA" : {
              "service": "<REPLACE WITH YOUR MESSAGING SERVICE>",
              "address": "topic:<REPLACE WITH YOUR TOPIC>",
              "reliable": false
            },
            "myOutB" : {
              "service": "<REPLACE WITH YOUR MESSAGING SERVICE>",
              "address": "topic:<REPLACE WITH YOUR TOPIC>",
              "reliable": false
            }
          }
        }
```

Please check.
Thanks,
Steffen

**Comment by pradeeppanda-sap** [comment]
thanks for help in fixing it.

**Comment by SchroederSteffen** [comment]
Looks good now, thanks! 👍
