### ISSUE TITLE
Req. Product details - Activation of Capabilities failing - US region

### ISSUE THREAD

**Issue by i353590** [SAPDocuments/Issues#540]
Hello,

Tutorial Link: https://developers.sap.com/tutorials/cp-starter-isuite-onboard-subscribe.html
Step 3: Provision the capabilities
Issue: Both the capabilities - API management and Cloud Integration are failing to activate.

![image](https://user-images.githubusercontent.com/66831161/128849580-318f6914-d0d5-498d-8726-3d092b2dfd58.png)

Please check the issue.

Thanks,
Shubham 

Labels to be added:
Sprint Label: SCPTest-2108A
Scenario Label: SCPTest-cloudin
Landscape Label: US10
Prio: High-prio

**Comment by Karunaharan** [comment]
Hi @i353590 - there was a known outage with the trial system which is resolved. Kindly proceed with your testing.

**Comment by i353590** [comment]
Hello @Karunaharan,

The provisioning of API management is still failing in US region. Though, the CI gets activated now, but API still fails.
Please re-open the ticket.

Best Regards,
Shubham A

**Comment by lalithmanokar** [comment]
Reopening ticket, issue still persist

**Comment by Karunaharan** [comment]
Hi @lalithmanokar - checked with the provisioning team and there seems to be no issues in provisioning the capabilities in all 3 regions. Could you please check again?

**Comment by i353590** [comment]
Hello @Karunaharan ,

The issue is still reproducible in US region.
Provisioning of API Management still fails
Please re-open the ticket & check once again from your side.

Thanks,
Shubham

**Comment by Karunaharan** [comment]
The issue is resolved today.

**Comment by i353590** [comment]
Hello,

I retested and the issue was not reproducible now.

Thanks,
Shubham
